# Generated by Django 4.2.8 on 2024-01-22 21:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import portal_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=11)),
                ('status', models.CharField(choices=[('O', 'open'), ('C', 'closed')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(20), django.core.validators.RegexValidator('^[A-Za-z0-9_]*[a-zA-Z]+[A-Za-z0-9_]*$')])),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('user_type', models.CharField(choices=[('P', 'patient'), ('C', 'Clinic staff')], max_length=1)),
                ('phone_number', models.CharField(max_length=11, validators=[portal_app.validators.phone_validator])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_time', models.DateTimeField()),
                ('reservation_status', models.CharField(choices=[('R', 'reserved'), ('C', 'canceled'), ('P', 'pending')], max_length=1)),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_app.clinic')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_app.user')),
            ],
        ),
    ]
