# Generated by Django 4.2.8 on 2024-01-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='dr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='portal_app.user'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_reserved_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_appointments', to='portal_app.user'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='clinic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_appointments', to='portal_app.clinic'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reservation_status',
            field=models.CharField(choices=[('R', 'reserved'), ('C', 'canceled'), ('NR', 'not reserved')], default=('NR', 'not reserved'), max_length=2),
        ),
    ]
