# Generated by Django 4.2.8 on 2024-01-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0003_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reservation_status',
            field=models.CharField(choices=[('R', 'reserved'), ('C', 'canceled'), ('NR', 'not reserved')], default='NR', max_length=2),
        ),
    ]
