# Generated by Django 4.2.8 on 2024-02-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0005_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
