# Generated by Django 4.2.8 on 2024-02-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0006_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='clinic_id',
            new_name='clinic',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='dr_id',
            new_name='dr',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_reserved_id',
            new_name='patient_reserved',
        ),
    ]
